### ISSUE TITLE
Build on Raspberry Pi 3b fails (Raspbian Jessie)

### ISSUE THREAD

**Issue by jrie** [hypersad/atom#9]
Hello,

using the version of today, the build on Raspberry Pi 3b, running an up to date Raspbian, fails due to errors. The build environment is setup according to the guides provided in this repository.

I should mention, I did not start the build script as root and the root user is not aware of node or nvm.

Please have a look at the build output and let me know if there can be something done about to resolve the issue.

```
pi@raspberrypi:~/Schreibtisch/atom $ node script/build
Node:	v6.10.2
Npm:	v3.10.10
Installing script dependencies
Installing apm
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
Installing modules ✓
Installing atom-dark-syntax@0.28.0 ✓
Installing atom-dark-ui@0.53.0 ✓
Installing atom-light-syntax@0.29.0 ✓
Installing atom-light-ui@0.46.0 ✓
Installing base16-tomorrow-dark-theme@1.5.0 ✓
Installing base16-tomorrow-light-theme@1.5.0 ✓
Installing one-dark-ui@1.9.1 ✓
Installing one-light-ui@1.9.1 ✓
Installing one-dark-syntax@1.7.1 ✓
Installing one-light-syntax@1.7.1 ✓
Installing solarized-dark-syntax@1.1.2 ✓
Installing solarized-light-syntax@1.1.2 ✓
Installing about@1.7.2 ✓
Installing archive-view@0.62.2 ✓
Installing autocomplete-atom-api@0.10.0 ✓
Installing autocomplete-css@0.15.0 ✓
Installing autocomplete-html@0.7.2 ✓
Installing autocomplete-plus@2.34.2 ✓
Installing autocomplete-snippets@1.11.0 ✓
Installing autoflow@0.29.0 ✓
Installing autosave@0.24.0 ✓
Installing background-tips@0.26.1 ✓
Installing bookmarks@0.44.1 ✓
Installing bracket-matcher@0.85.2 ✓
Installing command-palette@0.40.1 ✓
Installing deprecation-cop@0.56.2 ✓
Installing dev-live-reload@0.47.0 ✓
Installing encoding-selector@0.23.1 ✓
Installing exception-reporting@0.41.0 ✓
Installing find-and-replace@0.206.3 ✓
Installing fuzzy-finder@1.4.1 ✓
Installing git-diff@1.3.1 ✓
Installing go-to-line@0.32.0 ✓
Installing grammar-selector@0.49.1 ✓
Installing image-view@0.60.0 ✓
Installing incompatible-packages@0.26.1 ✓
Installing keybinding-resolver@0.36.1 ✓
Installing line-ending-selector@0.6.1 ✓
Installing link@0.31.2 ✓
Installing markdown-preview@0.159.6 ✓
Installing metrics@1.1.3 ✓
Installing notifications@0.66.2 ✓
Installing open-on-github@1.2.1 ✓
Installing package-generator@1.1.0 ✓
Installing settings-view@0.247.0 ✓
Installing snippets@1.0.5 ✓
Installing spell-check@0.70.2 ✓
Installing status-bar@1.8.1 ✓
Installing styleguide@0.49.2 ✓
Installing symbols-view@0.114.0 ✓
Installing tabs@0.104.1 ✓
Installing timecop@0.34.0 ✓
Installing tree-view@0.214.1 ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.36.0 ✓
Installing whitespace@0.36.2 ✓
Installing wrap-guide@0.39.0 ✓
Installing language-c@0.56.0 ✓
Installing language-clojure@0.22.2 ✓
Installing language-coffee-script@0.48.5 ✓
Installing language-csharp@0.14.2 ✓
Installing language-css@0.42.0 ✓
Installing language-gfm@0.88.1 ✓
Installing language-git@0.19.0 ✓
Installing language-go@0.43.1 ✓
Installing language-html@0.47.2 ✓
Installing language-hyperlink@0.16.1 ✓
Installing language-java@0.26.0 ✓
Installing language-javascript@0.126.1 ✓
Installing language-json@0.18.3 ✓
Installing language-less@0.30.1 ✓
Installing language-make@0.22.3 ✓
Installing language-mustache@0.13.1 ✓
Installing language-objective-c@0.15.1 ✓
Installing language-perl@0.37.0 ✓
Installing language-php@0.37.4 ✓
Installing language-property-list@0.9.0 ✓
Installing language-python@0.45.2 ✓
Installing language-ruby@0.70.5 ✓
Installing language-ruby-on-rails@0.25.2 ✓
Installing language-sass@0.57.1 ✓
Installing language-shellscript@0.25.0 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.25.3 ✓
Installing language-text@0.7.1 ✓
Installing language-todo@0.29.1 ✓
Installing language-toml@0.18.1 ✓
Installing language-xml@0.34.16 ✓
Installing language-yaml@0.28.0 ✓
Wrote Dependencies Fingerprint: /home/pi/Schreibtisch/atom/node_modules/.dependencies-fingerprint 1378bc15a3a7190fe2ea8d12d9ba9dc81033cd7e
Copying assets to /home/pi/Schreibtisch/atom/out/app
Transpiling Babel paths in /home/pi/Schreibtisch/atom/out/app
Transpiling CoffeeScript paths in /home/pi/Schreibtisch/atom/out/app
Transpiling CSON paths in /home/pi/Schreibtisch/atom/out/app
Transpiling PEG.js paths in /home/pi/Schreibtisch/atom/out/app
Generating module cache for /home/pi/Schreibtisch/atom/out/app
Generating pre-built less cache in /home/pi/Schreibtisch/atom/out/app/less-compile-cache
Generating metadata for /home/pi/Schreibtisch/atom/out/app/package.json
Generating API docs at /home/pi/Schreibtisch/atom/docs/output/atom-api.json
Dumping symbols in /home/pi/Schreibtisch/atom/out/symbols
Running electron-packager on /home/pi/Schreibtisch/atom/out/app with app name "atom"
WARNING: The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
WARNING: The app-copyright parameter is deprecated when used from JS, use appCopyright instead. It will be removed in the next major version.
WARNING: The app-version parameter is deprecated when used from JS, use appVersion instead. It will be removed in the next major version.
WARNING: The build-version parameter is deprecated when used from JS, use buildVersion instead. It will be removed in the next major version.
WARNING: The app-bundle-id parameter is deprecated when used from JS, use appBundleId instead. It will be removed in the next major version.
WARNING: The extend-info parameter is deprecated when used from JS, use extendInfo instead. It will be removed in the next major version.
WARNING: The helper-bundle-id parameter is deprecated when used from JS, use helperBundleId instead. It will be removed in the next major version.
Downloading SHASUMS256.txt
[============================================>] 100.0% of 2.88 kB (2.88 kB/s)
Packaging app for platform linux armv7l using electron v1.4.16
Changing permissions for node files in /home/pi/Schreibtisch/atom/out/atom-1.15.0-armv7l
Error: spawnSync /bin/sh ENOMEM
    at exports._errnoException (util.js:1018:11)
    at spawnSync (child_process.js:459:20)
    at Object.execSync (child_process.js:515:13)
    at chmodNodeFiles (/home/pi/Schreibtisch/atom/script/lib/package-application.js:96:16)
    at runPackager.then (/home/pi/Schreibtisch/atom/script/lib/package-application.js:46:7)
```

**Comment by hypersad** [comment]
Hello! ENOMEM error means, that you RAM ended during installation. Try to close all odd processes, tasks and start building again.

**Comment by djarami** [comment]
I ran into that and rebooting was better.

**Comment by jrie** [comment]
I will give that a shoot, perhaps the RAM configuration can be tweaked to give a little bit more RAM space for the build process... I think I use a 768/256 "Memory Split"  for OS/GPU in my Pi3 config.

Unfortunately I didn't run any other processes during that time, which might consume a lot of RAM either. I can try to have a look at "atop" / "htop" output during the build so.

**Comment by djarami** [comment]
I also did it ssh'd into the Pi without VNC connection.

**Comment by jrie** [comment]
Increasing the swap file size did it for me - I am just not aware how much RAM actually was used, but I offered 2048 MB as swap. Instead of the initial 100 MB - which just did not seem to be enough.

@djarami : Can you tell me, after compiling, how do I get on with installing Atom once everything is build?
Its not in the guide itself and runnin "atom.sh" after installation, raised an error for me.

Im currently building it using _node script/build --install_ so. Perhaps I should be patient, but it takes quite some time and the PI is getting quite hot during the build itself. Im very happy so it has heatsinks.

**Comment by jrie** [comment]
Atom is running now, it took some time on startup and didnt respond for some moments, but after the initial "hick up", its working well.

I didn't try to do something extra ordinary, just opened some project, opened up some code and tested if the autocompletion is working, so far so good.

Thank you very much for your efforts, finally Atom on the Raspberry Pi! 👍

**Comment by hypersad** [comment]
I think there is no neccesarily to allocate more RAM using swap or other tools. I've build it always with 1GB RAM where is 300MB usually taken by XServer. Thanks for you testing. I think, I can close this issue.

**Comment by jrie** [comment]
Yes, the issue can be closed. Thank you.
Atom is running well.

**Comment by marriotb** [comment]
Just clarifying @jrie's comments above about both swap size and the process of installation, I have it installed on a RPi 3B without changing any swap settings from default. I did have to create the Debian package and then install that using dpkg as root via sudo. All seems to work fine.

**Comment by jrie** [comment]
I did another installation on a different Pi3b and all worked well without making any changes to the swap or similar. So the changes are most likely not required - in any way it can be a good point to continue the build process, if for any reason it fails in first place.

Other then that all seems to be run well.
